#!/usr/bin/env bash
# script that pings an IP address passed as an argument

# IP variable
IP="${1}"

# Script filename
fn=$(basename "${0}")

if ! [ "$IP" ]; then
    echo "Usage: ${fn} {IP_ADDRESS}"
else
    ping -c 5 "${IP}"
fi

