#!/bin/bash

# Check if argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Assign the IP address to a variable
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 $IP_ADDRESS

